spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.95.218.254:3306/mailuo_sd?useSSL=false&charset='UTF8'&allowPublicKeyRetrieval=true
      username: mailuo
      password: xb_PXR9jL_x=
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 6000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 6000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-connect-error-millis: 3000
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: wsc
      filter: stat,wall,log4j2
mybatis-plus:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath:mybatis/mapper/extension/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage:  com.work.demos.mybatis.spider.entity
  #    typeEnumsPackage: com.baomidou.springboot.db.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      tablePrefix: t_
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #            field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
elasticsearch:
  ip: 39.106.176.242,59.110.165.218
  tumorIndex: mailuo_tumour_test
  reportIndex: mailuo_report_test
server:
  servlet:
    session:
      timeout: PT10m
  port: 8080